### ISSUE TITLE
Unhandled exception. MemoryPack.MemoryPackSerializationException: Length header size is larger than buffer size

### ISSUE THREAD

**Issue by Qwerky9** [LukeFZ/PrismCatalogDownloader#2]
I don't know if this is the problem with my compiler or what. I tried 
`PrismCatalogDownloader.exe 1.0.4 10000300@jqWxJ9wcJQVnmMwPYKbgEDA= path `
and It was working well until it hit at Downloading liveresult_sad_28_animparam.json... and here's the error 

```
Unhandled exception. MemoryPack.MemoryPackSerializationException: Length header size is larger than buffer size, length: 84466661.
   at MemoryPack.MemoryPackSerializationException.ThrowInsufficientBufferUnless(Int32 length)
   at PRISM.Definitions.MstEventStory.MemoryPack.IMemoryPackable<PRISM.Definitions.MstEventStory>.Deserialize(MemoryPackReader& reader, MstEventStory& value) in D:\PrismCatalogDownloader-master\PrismCatalogDownloader-master\PrismCatalogDownloader\MemoryPack.Generator\MemoryPack.Generator.MemoryPackGenerator\PRISM.Definitions.MstEventStory.MemoryPackFormatter.g.cs:line 116
   at MemoryPack.Formatters.MemoryPackableFormatter`1.Deserialize(MemoryPackReader& reader, T& value)
   at MemoryPack.Formatters.DictionaryFormatter`2.Deserialize(MemoryPackReader& reader, Dictionary`2& value)
   at PRISM.Definitions.MasterData.MemoryPack.IMemoryPackable<PRISM.Definitions.MasterData>.Deserialize(MemoryPackReader& reader, MasterData& value) in D:\PrismCatalogDownloader-master\PrismCatalogDownloader-master\PrismCatalogDownloader\MemoryPack.Generator\MemoryPack.Generator.MemoryPackGenerator\PRISM.Definitions.MasterData.MemoryPackFormatter.g.cs:line 1120
   at MemoryPack.Formatters.MemoryPackableFormatter`1.Deserialize(MemoryPackReader& reader, T& value)
   at MemoryPack.MemoryPackSerializer.Deserialize[T](ReadOnlySpan`1 buffer, T& value, MemoryPackSerializerOptions options)
   at MemoryPack.MemoryPackSerializer.Deserialize[T](ReadOnlySpan`1 buffer, MemoryPackSerializerOptions options)
   at PrismCatalogDownloader.Program.Main(String[] args) in D:\PrismCatalogDownloader-master\PrismCatalogDownloader-master\PrismCatalogDownloader\Program.cs:line 107
   at PrismCatalogDownloader.Program.<Main>(String[] args) 
```

So is this my own problem?
If so please let me know and I will appreciate it in advance.

**Comment by LukeFZ** [comment]
The files all downloaded fine, it just can't deserialize the masterdata due to it being in an old format and the tool only supporting the newest one. downgrade if you actually need the masterdata, otherwise you can ignore the error.
